apiVersion: v1
kind: Pod
metadata:
  name: dns-probe
  namespace: app
spec:
  containers:
  - name: probe
    image: busybox
    command:
    - /bin/sh
    - -c
    - |
      while true; do
        echo "$(date) - $(nslookup kubernetes.default.svc.cluster.local)" >> /probe/output.log;
        sleep 5;
      done
    volumeMounts:
    - name: probe-logs
      mountPath: /probe
  volumes:
  - name: probe-logs
    emptyDir: {}
  restartPolicy: Always
