apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cluster.name }}-db-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  username: {{ .Values.database.username | quote }}
  password: {{ .Values.database.password | quote }}