apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: red-team-project
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: Red Team Project

  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - 'https://github.com/mmoreiradj/cluster-panic-gitops.git'
  # Only permit applications to deploy to the 'guestbook' namespace or any namespace starting with 'guestbook-' in the same cluster
  # Destination clusters can be identified by 'server', 'name', or both.
  destinations:
  - namespace: app-namespace
    server: https://kubernetes.default.svc
    name: in-cluster
  # Deny all cluster-scoped resources from being created, except for Namespace
  clusterResourceWhitelist: []
  # Deny all namespaced-scoped resources from being created, except for Deployment and StatefulSet
  namespaceResourceWhitelist:
  - group: 'apps'
    kind: Deployment
  - group: 'apps'
    kind: StatefulSet
  - group: ''
    kind: ConfigMap
  - group: ''
    kind: Secret
  - group: ''
    kind: Service
  # Enables namespace orphaned resource monitoring.
  orphanedResources:
    warn: false

  roles: []
