apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: red-team-read-all
subjects:
- kind: User
  name: red-team-user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: red-team-read-all
  apiGroup: rbac.authorization.k8s.io
