apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: red-team
  namespace: app-namespace
subjects:
- kind: User
  name: red-team-user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: red-team
  apiGroup: rbac.authorization.k8s.io
