apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: red-team
  namespace: app-namespace
rules:
- apiGroups: [ "apps" ]
  resources: [ "deployments", "statefulsets" ]
  verbs: [ "*" ]
- apiGroups: [ "" ]
  resources: [ "pods", "configmaps", "secrets" ]
  verbs: [ "*" ]
