apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: db-namespace
type: kubernetes.io/basic-auth
stringData:
  username: postgres
  password: postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: app-namespace
stringData:
  PG_NAME: postgres
  PG_USER: postgres
  PG_PASSWORD: postgres
  PG_HOST: postgres-rw.db-namespace.svc.cluster.local
