---
# Source: backend/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-backend
  labels:
    helm.sh/chart: backend-0.1.0
    app.kubernetes.io/name: backend
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: backend
    app.kubernetes.io/instance: release-name
---
# Source: backend/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-backend
  labels:
    helm.sh/chart: backend-0.1.0
    app.kubernetes.io/name: backend
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: backend
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        helm.sh/chart: backend-0.1.0
        app.kubernetes.io/name: backend
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/version: "1.16.0"
        app.kubernetes.io/managed-by: Helm
    spec:
      securityContext:
        runAsUser: 1001
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: backend
        securityContext:
          capabilities:
            drop:
            - ALL
          allowPrivilegeEscalation: false
        image: "docker.io/thomasmauran/kube-blindax-backend:latest"
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        livenessProbe: null
        readinessProbe: null
        resources: {}
        env:
        - name: DB_USER
          value: app
        - name: DB_USER
          value: app
        - name: DB_PASSWORD
          value: app
        - name: DB_HOST
          value: postgres-rw.db-namespace.svc.cluster.local
        - name: DB_NAME
          value: app
        - name: DB_PORT
          value: "5432"
        - name: PORT
          value: "80"
---


