apiVersion: v1
kind: Pod
metadata:
  namespace: app-namespace
  labels:
    run: busybox
  name: busybox
spec:
  automountServiceAccountToken: true
  securityContext:
    runAsUser: 1001
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
  - image: ghcr.io/containerd/busybox:1.36
    name: busybox
    command:
    - sleep
    - infinity
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
    securityContext:
      capabilities:
        drop:
        - ALL
      allowPrivilegeEscalation: false
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
