apiVersion: v1
kind: Pod
metadata:
  namespace: app-namespace
  labels:
    run: nginx
  name: nginx
spec:
  automountServiceAccountToken: true
  securityContext:
    runAsUser: 1001
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
  - image: ghcr.io/linuxserver/nginx:1.26.3-r0-ls317
    name: nginx
    resources: {}
    securityContext:
      capabilities:
        drop:
        - ALL
      allowPrivilegeEscalation: false
    volumeMounts:
    - name: cache
      mountPath: /var/cache/nginx
    - name: run
      mountPath: /run
  volumes:
  - name: cache
    emptyDir: {}
  - name: run
    emptyDir: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
