apiVersion: v1
kind: Pod
metadata:
  namespace: db-namespace
  labels:
    run: nginx
  name: nginx
spec:
  automountServiceAccountToken: true
  containers:
  - image: nginx
    name: nginx
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
