apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dns-nuke-hpa
  namespace: app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dns-nuke
  minReplicas: 10
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
