apiVersion: v1
kind: Pod
metadata:
  name: sleeper
  namespace: app
spec:
  containers:
  - name: sleeper
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "sleep 3600"]
  restartPolicy: Never
