apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: mutate-pod-bandwidth
  annotations:
    policies.kyverno.io/title: Mutate Pod Bandwidth
    policies.kyverno.io/category: Security
    policies.kyverno.io/severity: High
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      This policy mutates Pods to set a bandwidth limit of 10MiB/s for all containers.
spec:
  rules:
    - name: set-bandwidth-limit
      match:
        resources:
          kinds:
            - Pod
          namespaces:
            - app-namespace
      mutate:
        patchStrategicMerge:
          metadata:
            annotations:
              kubernetes.io/egress-bandwidth: "10M"
              kubernetes.io/ingress-bandwidth: "10M"
