apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: mutate-hardening
  namespace: app-namespace
spec:
  rules:
  - name: disable-automount-service-account-token
    match:
      all:
      - resources:
          kinds:
          - Pod
    mutate:
      patchStrategicMerge:
        spec:
          automountServiceAccountToken: false
