apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: mutate-automount-sa-token
  annotations:
    policies.kyverno.io/title: Mutate Automount Service Account Token
    policies.kyverno.io/category: Security
    policies.kyverno.io/severity: High
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      This policy mutates Pods to set automountServiceAccountToken to false for all containers.
spec:
  rules:
  - name: set-automount-sa-token
    match:
      resources:
        kinds:
        - Pod
        namespaces:
        - app-namespace
    mutate:
      patchStrategicMerge:
        spec:
          automountServiceAccountToken: false
