# Prevent too many replicas in a pod
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: prevent-too-many-replicas
  annotations:
    policies.kyverno.io/title: Prevent Too Many Replicas
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Deployment, StatefulSet, Pod
    policies.kyverno.io/description: >-
      This policy prevents having too many replicas for workloads.
spec:
  validationFailureAction: Enforce
  background: true
  rules:
  - name: prevent-too-many-replicas
    match:
      resources:
        kinds:
        - Deployment
        - StatefulSet
        namespaces:
        - app-namespace
    validate:
      message: "Too many replicas"
      deny:
        conditions:
        - key: "spec.replicas"
          operator: "GreaterThan"
          value: "3"
