apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: db-namespace
type: kubernetes.io/basic-auth
stringData:
  username: app
  password: app
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: app-namespace
stringData:
  PG_NAME: app
  PG_USER: app
  PG_PASSWORD: app
  PG_HOST: postgres-rw.db-namespace.svc.cluster.local
