apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: db-namespace
spec:
  instances: 1

  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: postgres-secrets

  storage:
    storageClass: local-path
    size: 40Gi
