apiVersion: v1
kind: LimitRange
metadata:
  name: strict-limits
  namespace: app-namespace
spec:
  limits:
  - default:
      cpu: 100m
      memory: 128Mi
    defaultRequest:
      cpu: 50m
      memory: 64Mi
    max:
      cpu: 200m
      memory: 256Mi
    min:
      cpu: 10m
      memory: 32Mi
    type: Container
