apiVersion: v1
kind: ResourceQuota
metadata:
  name: strict-quotas
  namespace: app-namespace
spec:
  hard:
    pods: "5"
    configmaps: "2"
    secrets: "2"
    services: "5"
    requests.cpu: "2"
    requests.memory: "1.5Gi"
    limits.cpu: "2"
    limits.memory: "1.5Gi"
    hugepages-2Mi: "0"
    hugepages-1Gi: "0"
    persistentvolumeclaims: "2"
    replicationcontrollers: "0"
