apiVersion: v1
kind: ResourceQuota
metadata:
  name: strict-quotas
  namespace: app-namespace
spec:
  hard:
    pods: "5"
    configmaps: "2"
    secrets: "2"
    services: "5"
    requests.cpu: "1000m" # 5 x 200m
    requests.memory: "1280Mi" # 5 x 256Mi
    limits.cpu: "1000m" # 5 x 200m
    limits.memory: "1280Mi" # 5 x 256Mi
    hugepages-2Mi: "0"
    hugepages-1Gi: "0"
    persistentvolumeclaims: "2"
    replicationcontrollers: "0"
