kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: red-team-manifests
  namespace: fleet-local
spec:
  repo: https://github.com/mmoreiradj/cluster-panic-gitops
  targetNamespace: app-namespace
  branch: main
  paths:
  - manifests/red-team
  pollingInterval: 15s
  deleteNamespace: true
